---
apiVersion: v1
kind: Namespace
metadata:
  name: ng2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-deployment-v2
  namespace: ng2
  labels:
    app: ng2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng2
  template:
    metadata:
      labels:
        app: ng2
        version: v2
    spec:
      containers:
      - name: ng-v2
        image: tomcat
        imagePullPolicy: Always
        env:       
        - name: "SVC_VER"
          value: "2"                  
        ports:
        - name: product
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ng-service-v2
  namespace: ng2
  labels:
    app: ng2
    version: v2
spec:
  selector:
    app: ng2
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ng2-gateway
  namespace: ng2
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ng2.ru"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ng2-virtualservice
  namespace: ng2
spec:
  hosts:
  - "ng2.ru"
  gateways:
  - ng2-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: "ng-service-v2"
        port:
          number: 80