---
apiVersion: v1
kind: Namespace
metadata:
  name: ng

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-deployment-v1
  namespace: ng
  labels:
    app: ng1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng1
  template:
    metadata:
      labels:
        app: ng1
        version: v1
    spec:
      containers:
      - name: ng-v1
        image: nginx
        imagePullPolicy: Always
        env:       
        - name: "SVC_VER"
          value: "1" 
        ports:
        - name: product
          containerPort: 80                
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "echo Wellcome to ng1.ru Version 1111 > /usr/share/nginx/html/index.html"]

---
apiVersion: v1
kind: Service
metadata:
  name: ng-service-v1
  namespace: ng
  labels:
    app: ng1
    version: v1
spec:
  selector:
    app: ng1
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ng-gateway
  namespace: ng
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ng1.ru"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ng-virtualservice
  namespace: ng
spec:
  hosts:
  - "ng1.ru"
  gateways:
  - ng-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: "ng-service-v1"
        port:
          number: 80